# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: RunTests
  displayName: 'Run Tests'
  strategy:
    matrix:
      Python37:
        PYTHON_VERSION: '3.7'
      Python38:
        PYTHON_VERSION: '3.8'
      Python39:
        PYTHON_VERSION: '3.9'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PYTHON_VERSION)'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install Django
      pip install -r requirements.txt
      pip install unittest-xml-reporting
    displayName: 'Install prerequisites'

  - script: |
      python manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/TEST-*.xml"
      testRunTitle: 'Python $(PYTHON_VERSION)'
    condition: succeededOrFailed()

- job: DeployToAzure
  displayName: 'Deploy to Azure'
  dependsOn: RunTests
  condition: succeeded()
  steps:
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'django'
      appName: 'COM769PythonDjango'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
